/**
 * Type definitions and env/secret bindings (merging with worker-configuration.d.ts)
 */

export {};
// Bindings below auto-generated by `npx wrangler types`
// No need to define here
// export interface Env {
// 	// Binding for the workers AI API

// 	AI: Ai;

// 	// Binding for static assets.
// 	ASSETS: { fetch: (request: Request) => Promise<Response> };

// 	// Binding for telegram bot token/secret
// 	TELEGRAM_BOT_TOKEN: string;

// 	// Binding for other tokens/secrets
// 	MY_FIRST_TOKEN: string;

// 	// Binding KV
// 	HACKER_NEWS_WORKER: KVNamespace;
// }

declare global {
	namespace Cloudflare {
		interface Env {
			TEST_VARIABLE: 'test_value';
			KV_TTL_SECS: 14400;
			TELEGRAM_CHAT_ID: '@hacker_news_summary';
		}
	}
}
